version: '3.3'

services:
  postgres:
    image: postgres:14
    environment:
      POSTGRES_USER: user       # postgres user
      POSTGRES_PASSWORD: pass   # postgres password
    ports:
      - "5432:5432"             # postgres port
